// Generated by CoffeeScript 1.6.3
(function() {
  var app, widgets;

  widgets = [
    {
      name: 'combo'
    }, {
      name: 'select'
    }, {
      name: 'multiselect'
    }, {
      name: 'tags'
    }, {
      name: 'radio'
    }, {
      name: 'checkbox'
    }
  ];

  app = angular.module('angular-w-demo', ['angular-w', 'ngRoute', 'ngSanitize'], function($routeProvider, $locationProvider) {
    var w, _i, _len, _results;
    $routeProvider.when('/', {
      templateUrl: 'demo/templates/welcome.html'
    }).when('/formbuilder', {
      templateUrl: 'demo/formbuilder.html'
    });
    _results = [];
    for (_i = 0, _len = widgets.length; _i < _len; _i++) {
      w = widgets[_i];
      _results.push((function(w) {
        console.log(w.name);
        return $routeProvider.when("/widgets/" + w.name, {
          templateUrl: "demo/templates/" + w.name + ".html"
        });
      })(w));
    }
    return _results;
  });

  app.filter('prettify', function() {
    return function(code) {
      if (code) {
        return hljs.highlightAuto(code).value;
      }
    };
  });

  app.run(function($rootScope) {
    return $rootScope.widgets = widgets;
  });

  app.controller('WidgetCtrl', function($routeParams) {
    return console.log($routeParams);
  });

  app.directive('sample', function() {
    return {
      restrict: 'E',
      controller: function($scope) {
        return $scope.current = "demo";
      },
      template: function(el) {
        var html, js, orig;
        orig = el.html();
        js = hljs.highlightAuto($.trim($(el).find('script').remove().text())).value;
        html = hljs.highlightAuto($.trim(el.html())).value;
        return "<div>\n  <div class=\"btn-group\">\n    <a class=\"btn btn-default\" ng-click=\"current='demo'\">Demo</a>\n    <a class=\"btn btn-default\" ng-click=\"current='html'\">HTML</a>\n    <a class=\"btn btn-default\" ng-click=\"current='js'\">JavaScript</a>\n  </div>\n  <hr/>\n  <div ng-show=\"current=='demo'\">" + orig + "</div>\n  <div ng-show=\"current=='html'\"><pre>" + html + "</pre> </div>\n  <div ng-show=\"current=='js'\"><pre>" + js + "</pre> </div>\n</div>";
      }
    };
  });

}).call(this);
