require('./config')
require('./radio')
require('./list')
require('./input')
require('./checkbox')
require('./field')
require('./formFor')
require('./select')
require('./multiselect')
require('./time')
require('./timeFormat')
require('./dateFormat')
require('./date')
require('./calendar')
require('./datetime')

require("../styles/syntax.css")
